/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyRouteImport } from './routes/why'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SlaRouteImport } from './routes/sla'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LoginOtpRouteImport } from './routes/login-otp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as AuthenticatedClientRouteImport } from './routes/_authenticated/client'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedClientIndexRouteImport } from './routes/_authenticated/client.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as VerifyReceiptCodeRouteImport } from './routes/verify.receipt.$code'
import { Route as AuthenticatedClientWalletRouteImport } from './routes/_authenticated/client.wallet'
import { Route as AuthenticatedClientSupportRouteImport } from './routes/_authenticated/client.support'
import { Route as AuthenticatedClientServicesRouteImport } from './routes/_authenticated/client.services'
import { Route as AuthenticatedClientProjectsRouteImport } from './routes/_authenticated/client.projects'
import { Route as AuthenticatedClientProfileRouteImport } from './routes/_authenticated/client.profile'
import { Route as AuthenticatedClientPaymentsRouteImport } from './routes/_authenticated/client.payments'
import { Route as AuthenticatedClientNotificationsRouteImport } from './routes/_authenticated/client.notifications'
import { Route as AuthenticatedClientInvoicesRouteImport } from './routes/_authenticated/client.invoices'
import { Route as AuthenticatedClientFilesRouteImport } from './routes/_authenticated/client.files'
import { Route as AuthenticatedClientContractsRouteImport } from './routes/_authenticated/client.contracts'
import { Route as AuthenticatedAdminWalletRouteImport } from './routes/_authenticated/admin.wallet'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedAdminProjectRequestsRouteImport } from './routes/_authenticated/admin.project-requests'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin.invoices'
import { Route as AuthenticatedAdminFilesRouteImport } from './routes/_authenticated/admin.files'
import { Route as AuthenticatedAdminContractsRouteImport } from './routes/_authenticated/admin.contracts'
import { Route as AuthenticatedAdminAuditLogRouteImport } from './routes/_authenticated/admin.audit-log'
import { Route as AuthenticatedClientProjectsIndexRouteImport } from './routes/_authenticated/client.projects.index'
import { Route as AuthenticatedAdminProjectRequestsIndexRouteImport } from './routes/_authenticated/admin.project-requests.index'
import { Route as AuthenticatedAdminClientsIndexRouteImport } from './routes/_authenticated/admin.clients.index'
import { Route as AuthenticatedClientSupportIdRouteImport } from './routes/_authenticated/client.support.$id'
import { Route as AuthenticatedClientServicesIdRouteImport } from './routes/_authenticated/client.services.$id'
import { Route as AuthenticatedClientProjectsNewRouteImport } from './routes/_authenticated/client.projects.new'
import { Route as AuthenticatedClientProjectsIdRouteImport } from './routes/_authenticated/client.projects.$id'
import { Route as AuthenticatedClientPaymentsIdRouteImport } from './routes/_authenticated/client.payments.$id'
import { Route as AuthenticatedClientInvoicesIdRouteImport } from './routes/_authenticated/client.invoices.$id'
import { Route as AuthenticatedClientContractsIdRouteImport } from './routes/_authenticated/client.contracts.$id'
import { Route as AuthenticatedAdminSupportIdRouteImport } from './routes/_authenticated/admin.support.$id'
import { Route as AuthenticatedAdminProjectsIdRouteImport } from './routes/_authenticated/admin.projects.$id'
import { Route as AuthenticatedAdminProjectRequestsIdRouteImport } from './routes/_authenticated/admin.project-requests.$id'
import { Route as AuthenticatedAdminPaymentsIdRouteImport } from './routes/_authenticated/admin.payments.$id'
import { Route as AuthenticatedAdminInvoicesIdRouteImport } from './routes/_authenticated/admin.invoices.$id'
import { Route as AuthenticatedAdminContractsIdRouteImport } from './routes/_authenticated/admin.contracts.$id'
import { Route as AuthenticatedAdminClientsNewRouteImport } from './routes/_authenticated/admin.clients.new'
import { Route as AuthenticatedAdminClientsIdRouteImport } from './routes/_authenticated/admin.clients.$id'
import { Route as AuthenticatedClientProjectsRequestsIdRouteImport } from './routes/_authenticated/client.projects.requests.$id'
import { Route as AuthenticatedAdminClientsIdEditRouteImport } from './routes/_authenticated/admin.clients.$id.edit'

const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SlaRoute = SlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginOtpRoute = LoginOtpRouteImport.update({
  id: '/login-otp',
  path: '/login-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const AuthenticatedClientRoute = AuthenticatedClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientIndexRoute =
  AuthenticatedClientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const VerifyReceiptCodeRoute = VerifyReceiptCodeRouteImport.update({
  id: '/receipt/$code',
  path: '/receipt/$code',
  getParentRoute: () => VerifyRoute,
} as any)
const AuthenticatedClientWalletRoute =
  AuthenticatedClientWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientSupportRoute =
  AuthenticatedClientSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientServicesRoute =
  AuthenticatedClientServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientProjectsRoute =
  AuthenticatedClientProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientProfileRoute =
  AuthenticatedClientProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientPaymentsRoute =
  AuthenticatedClientPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientNotificationsRoute =
  AuthenticatedClientNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientInvoicesRoute =
  AuthenticatedClientInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientFilesRoute =
  AuthenticatedClientFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientContractsRoute =
  AuthenticatedClientContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedAdminWalletRoute =
  AuthenticatedAdminWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectRequestsRoute =
  AuthenticatedAdminProjectRequestsRouteImport.update({
    id: '/project-requests',
    path: '/project-requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFilesRoute = AuthenticatedAdminFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminContractsRoute =
  AuthenticatedAdminContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditLogRoute =
  AuthenticatedAdminAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedClientProjectsIndexRoute =
  AuthenticatedClientProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientProjectsRoute,
  } as any)
const AuthenticatedAdminProjectRequestsIndexRoute =
  AuthenticatedAdminProjectRequestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminProjectRequestsRoute,
  } as any)
const AuthenticatedAdminClientsIndexRoute =
  AuthenticatedAdminClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedClientSupportIdRoute =
  AuthenticatedClientSupportIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedClientSupportRoute,
  } as any)
const AuthenticatedClientServicesIdRoute =
  AuthenticatedClientServicesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedClientServicesRoute,
  } as any)
const AuthenticatedClientProjectsNewRoute =
  AuthenticatedClientProjectsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedClientProjectsRoute,
  } as any)
const AuthenticatedClientProjectsIdRoute =
  AuthenticatedClientProjectsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedClientProjectsRoute,
  } as any)
const AuthenticatedClientPaymentsIdRoute =
  AuthenticatedClientPaymentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedClientPaymentsRoute,
  } as any)
const AuthenticatedClientInvoicesIdRoute =
  AuthenticatedClientInvoicesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedClientInvoicesRoute,
  } as any)
const AuthenticatedClientContractsIdRoute =
  AuthenticatedClientContractsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedClientContractsRoute,
  } as any)
const AuthenticatedAdminSupportIdRoute =
  AuthenticatedAdminSupportIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminSupportRoute,
  } as any)
const AuthenticatedAdminProjectsIdRoute =
  AuthenticatedAdminProjectsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminProjectsRoute,
  } as any)
const AuthenticatedAdminProjectRequestsIdRoute =
  AuthenticatedAdminProjectRequestsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminProjectRequestsRoute,
  } as any)
const AuthenticatedAdminPaymentsIdRoute =
  AuthenticatedAdminPaymentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPaymentsRoute,
  } as any)
const AuthenticatedAdminInvoicesIdRoute =
  AuthenticatedAdminInvoicesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminInvoicesRoute,
  } as any)
const AuthenticatedAdminContractsIdRoute =
  AuthenticatedAdminContractsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminContractsRoute,
  } as any)
const AuthenticatedAdminClientsNewRoute =
  AuthenticatedAdminClientsNewRouteImport.update({
    id: '/clients/new',
    path: '/clients/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsIdRoute =
  AuthenticatedAdminClientsIdRouteImport.update({
    id: '/clients/$id',
    path: '/clients/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedClientProjectsRequestsIdRoute =
  AuthenticatedClientProjectsRequestsIdRouteImport.update({
    id: '/requests/$id',
    path: '/requests/$id',
    getParentRoute: () => AuthenticatedClientProjectsRoute,
  } as any)
const AuthenticatedAdminClientsIdEditRoute =
  AuthenticatedAdminClientsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedAdminClientsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/login-otp': typeof LoginOtpRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/sla': typeof SlaRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRouteWithChildren
  '/why': typeof WhyRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/client': typeof AuthenticatedClientRouteWithChildren
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsRouteWithChildren
  '/admin/files': typeof AuthenticatedAdminFilesRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRouteWithChildren
  '/admin/payments': typeof AuthenticatedAdminPaymentsRouteWithChildren
  '/admin/project-requests': typeof AuthenticatedAdminProjectRequestsRouteWithChildren
  '/admin/projects': typeof AuthenticatedAdminProjectsRouteWithChildren
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/wallet': typeof AuthenticatedAdminWalletRoute
  '/client/contracts': typeof AuthenticatedClientContractsRouteWithChildren
  '/client/files': typeof AuthenticatedClientFilesRoute
  '/client/invoices': typeof AuthenticatedClientInvoicesRouteWithChildren
  '/client/notifications': typeof AuthenticatedClientNotificationsRoute
  '/client/payments': typeof AuthenticatedClientPaymentsRouteWithChildren
  '/client/profile': typeof AuthenticatedClientProfileRoute
  '/client/projects': typeof AuthenticatedClientProjectsRouteWithChildren
  '/client/services': typeof AuthenticatedClientServicesRouteWithChildren
  '/client/support': typeof AuthenticatedClientSupportRouteWithChildren
  '/client/wallet': typeof AuthenticatedClientWalletRoute
  '/verify/receipt/$code': typeof VerifyReceiptCodeRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/client/': typeof AuthenticatedClientIndexRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRouteWithChildren
  '/admin/clients/new': typeof AuthenticatedAdminClientsNewRoute
  '/admin/contracts/$id': typeof AuthenticatedAdminContractsIdRoute
  '/admin/invoices/$id': typeof AuthenticatedAdminInvoicesIdRoute
  '/admin/payments/$id': typeof AuthenticatedAdminPaymentsIdRoute
  '/admin/project-requests/$id': typeof AuthenticatedAdminProjectRequestsIdRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/admin/support/$id': typeof AuthenticatedAdminSupportIdRoute
  '/client/contracts/$id': typeof AuthenticatedClientContractsIdRoute
  '/client/invoices/$id': typeof AuthenticatedClientInvoicesIdRoute
  '/client/payments/$id': typeof AuthenticatedClientPaymentsIdRoute
  '/client/projects/$id': typeof AuthenticatedClientProjectsIdRoute
  '/client/projects/new': typeof AuthenticatedClientProjectsNewRoute
  '/client/services/$id': typeof AuthenticatedClientServicesIdRoute
  '/client/support/$id': typeof AuthenticatedClientSupportIdRoute
  '/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/project-requests/': typeof AuthenticatedAdminProjectRequestsIndexRoute
  '/client/projects/': typeof AuthenticatedClientProjectsIndexRoute
  '/admin/clients/$id/edit': typeof AuthenticatedAdminClientsIdEditRoute
  '/client/projects/requests/$id': typeof AuthenticatedClientProjectsRequestsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/login-otp': typeof LoginOtpRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/sla': typeof SlaRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRouteWithChildren
  '/why': typeof WhyRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services': typeof ServicesIndexRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsRouteWithChildren
  '/admin/files': typeof AuthenticatedAdminFilesRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRouteWithChildren
  '/admin/payments': typeof AuthenticatedAdminPaymentsRouteWithChildren
  '/admin/projects': typeof AuthenticatedAdminProjectsRouteWithChildren
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/wallet': typeof AuthenticatedAdminWalletRoute
  '/client/contracts': typeof AuthenticatedClientContractsRouteWithChildren
  '/client/files': typeof AuthenticatedClientFilesRoute
  '/client/invoices': typeof AuthenticatedClientInvoicesRouteWithChildren
  '/client/notifications': typeof AuthenticatedClientNotificationsRoute
  '/client/payments': typeof AuthenticatedClientPaymentsRouteWithChildren
  '/client/profile': typeof AuthenticatedClientProfileRoute
  '/client/services': typeof AuthenticatedClientServicesRouteWithChildren
  '/client/support': typeof AuthenticatedClientSupportRouteWithChildren
  '/client/wallet': typeof AuthenticatedClientWalletRoute
  '/verify/receipt/$code': typeof VerifyReceiptCodeRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/client': typeof AuthenticatedClientIndexRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRouteWithChildren
  '/admin/clients/new': typeof AuthenticatedAdminClientsNewRoute
  '/admin/contracts/$id': typeof AuthenticatedAdminContractsIdRoute
  '/admin/invoices/$id': typeof AuthenticatedAdminInvoicesIdRoute
  '/admin/payments/$id': typeof AuthenticatedAdminPaymentsIdRoute
  '/admin/project-requests/$id': typeof AuthenticatedAdminProjectRequestsIdRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/admin/support/$id': typeof AuthenticatedAdminSupportIdRoute
  '/client/contracts/$id': typeof AuthenticatedClientContractsIdRoute
  '/client/invoices/$id': typeof AuthenticatedClientInvoicesIdRoute
  '/client/payments/$id': typeof AuthenticatedClientPaymentsIdRoute
  '/client/projects/$id': typeof AuthenticatedClientProjectsIdRoute
  '/client/projects/new': typeof AuthenticatedClientProjectsNewRoute
  '/client/services/$id': typeof AuthenticatedClientServicesIdRoute
  '/client/support/$id': typeof AuthenticatedClientSupportIdRoute
  '/admin/clients': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/project-requests': typeof AuthenticatedAdminProjectRequestsIndexRoute
  '/client/projects': typeof AuthenticatedClientProjectsIndexRoute
  '/admin/clients/$id/edit': typeof AuthenticatedAdminClientsIdEditRoute
  '/client/projects/requests/$id': typeof AuthenticatedClientProjectsRequestsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/login-otp': typeof LoginOtpRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/sla': typeof SlaRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRouteWithChildren
  '/why': typeof WhyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/client': typeof AuthenticatedClientRouteWithChildren
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/_authenticated/admin/contracts': typeof AuthenticatedAdminContractsRouteWithChildren
  '/_authenticated/admin/files': typeof AuthenticatedAdminFilesRoute
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRouteWithChildren
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRouteWithChildren
  '/_authenticated/admin/project-requests': typeof AuthenticatedAdminProjectRequestsRouteWithChildren
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRouteWithChildren
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/wallet': typeof AuthenticatedAdminWalletRoute
  '/_authenticated/client/contracts': typeof AuthenticatedClientContractsRouteWithChildren
  '/_authenticated/client/files': typeof AuthenticatedClientFilesRoute
  '/_authenticated/client/invoices': typeof AuthenticatedClientInvoicesRouteWithChildren
  '/_authenticated/client/notifications': typeof AuthenticatedClientNotificationsRoute
  '/_authenticated/client/payments': typeof AuthenticatedClientPaymentsRouteWithChildren
  '/_authenticated/client/profile': typeof AuthenticatedClientProfileRoute
  '/_authenticated/client/projects': typeof AuthenticatedClientProjectsRouteWithChildren
  '/_authenticated/client/services': typeof AuthenticatedClientServicesRouteWithChildren
  '/_authenticated/client/support': typeof AuthenticatedClientSupportRouteWithChildren
  '/_authenticated/client/wallet': typeof AuthenticatedClientWalletRoute
  '/verify/receipt/$code': typeof VerifyReceiptCodeRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/client/': typeof AuthenticatedClientIndexRoute
  '/_authenticated/admin/clients/$id': typeof AuthenticatedAdminClientsIdRouteWithChildren
  '/_authenticated/admin/clients/new': typeof AuthenticatedAdminClientsNewRoute
  '/_authenticated/admin/contracts/$id': typeof AuthenticatedAdminContractsIdRoute
  '/_authenticated/admin/invoices/$id': typeof AuthenticatedAdminInvoicesIdRoute
  '/_authenticated/admin/payments/$id': typeof AuthenticatedAdminPaymentsIdRoute
  '/_authenticated/admin/project-requests/$id': typeof AuthenticatedAdminProjectRequestsIdRoute
  '/_authenticated/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/_authenticated/admin/support/$id': typeof AuthenticatedAdminSupportIdRoute
  '/_authenticated/client/contracts/$id': typeof AuthenticatedClientContractsIdRoute
  '/_authenticated/client/invoices/$id': typeof AuthenticatedClientInvoicesIdRoute
  '/_authenticated/client/payments/$id': typeof AuthenticatedClientPaymentsIdRoute
  '/_authenticated/client/projects/$id': typeof AuthenticatedClientProjectsIdRoute
  '/_authenticated/client/projects/new': typeof AuthenticatedClientProjectsNewRoute
  '/_authenticated/client/services/$id': typeof AuthenticatedClientServicesIdRoute
  '/_authenticated/client/support/$id': typeof AuthenticatedClientSupportIdRoute
  '/_authenticated/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/_authenticated/admin/project-requests/': typeof AuthenticatedAdminProjectRequestsIndexRoute
  '/_authenticated/client/projects/': typeof AuthenticatedClientProjectsIndexRoute
  '/_authenticated/admin/clients/$id/edit': typeof AuthenticatedAdminClientsIdEditRoute
  '/_authenticated/client/projects/requests/$id': typeof AuthenticatedClientProjectsRequestsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/acceptable-use'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/login-otp'
    | '/portfolio'
    | '/privacy'
    | '/process'
    | '/sla'
    | '/support'
    | '/terms'
    | '/verify'
    | '/why'
    | '/admin'
    | '/client'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/services/'
    | '/admin/audit-log'
    | '/admin/contracts'
    | '/admin/files'
    | '/admin/invoices'
    | '/admin/payments'
    | '/admin/project-requests'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/wallet'
    | '/client/contracts'
    | '/client/files'
    | '/client/invoices'
    | '/client/notifications'
    | '/client/payments'
    | '/client/profile'
    | '/client/projects'
    | '/client/services'
    | '/client/support'
    | '/client/wallet'
    | '/verify/receipt/$code'
    | '/admin/'
    | '/client/'
    | '/admin/clients/$id'
    | '/admin/clients/new'
    | '/admin/contracts/$id'
    | '/admin/invoices/$id'
    | '/admin/payments/$id'
    | '/admin/project-requests/$id'
    | '/admin/projects/$id'
    | '/admin/support/$id'
    | '/client/contracts/$id'
    | '/client/invoices/$id'
    | '/client/payments/$id'
    | '/client/projects/$id'
    | '/client/projects/new'
    | '/client/services/$id'
    | '/client/support/$id'
    | '/admin/clients/'
    | '/admin/project-requests/'
    | '/client/projects/'
    | '/admin/clients/$id/edit'
    | '/client/projects/requests/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/acceptable-use'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/login-otp'
    | '/portfolio'
    | '/privacy'
    | '/process'
    | '/sla'
    | '/support'
    | '/terms'
    | '/verify'
    | '/why'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/services'
    | '/admin/audit-log'
    | '/admin/contracts'
    | '/admin/files'
    | '/admin/invoices'
    | '/admin/payments'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/wallet'
    | '/client/contracts'
    | '/client/files'
    | '/client/invoices'
    | '/client/notifications'
    | '/client/payments'
    | '/client/profile'
    | '/client/services'
    | '/client/support'
    | '/client/wallet'
    | '/verify/receipt/$code'
    | '/admin'
    | '/client'
    | '/admin/clients/$id'
    | '/admin/clients/new'
    | '/admin/contracts/$id'
    | '/admin/invoices/$id'
    | '/admin/payments/$id'
    | '/admin/project-requests/$id'
    | '/admin/projects/$id'
    | '/admin/support/$id'
    | '/client/contracts/$id'
    | '/client/invoices/$id'
    | '/client/payments/$id'
    | '/client/projects/$id'
    | '/client/projects/new'
    | '/client/services/$id'
    | '/client/support/$id'
    | '/admin/clients'
    | '/admin/project-requests'
    | '/client/projects'
    | '/admin/clients/$id/edit'
    | '/client/projects/requests/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/acceptable-use'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/login-otp'
    | '/portfolio'
    | '/privacy'
    | '/process'
    | '/sla'
    | '/support'
    | '/terms'
    | '/verify'
    | '/why'
    | '/_authenticated/admin'
    | '/_authenticated/client'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/services/'
    | '/_authenticated/admin/audit-log'
    | '/_authenticated/admin/contracts'
    | '/_authenticated/admin/files'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/project-requests'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/wallet'
    | '/_authenticated/client/contracts'
    | '/_authenticated/client/files'
    | '/_authenticated/client/invoices'
    | '/_authenticated/client/notifications'
    | '/_authenticated/client/payments'
    | '/_authenticated/client/profile'
    | '/_authenticated/client/projects'
    | '/_authenticated/client/services'
    | '/_authenticated/client/support'
    | '/_authenticated/client/wallet'
    | '/verify/receipt/$code'
    | '/_authenticated/admin/'
    | '/_authenticated/client/'
    | '/_authenticated/admin/clients/$id'
    | '/_authenticated/admin/clients/new'
    | '/_authenticated/admin/contracts/$id'
    | '/_authenticated/admin/invoices/$id'
    | '/_authenticated/admin/payments/$id'
    | '/_authenticated/admin/project-requests/$id'
    | '/_authenticated/admin/projects/$id'
    | '/_authenticated/admin/support/$id'
    | '/_authenticated/client/contracts/$id'
    | '/_authenticated/client/invoices/$id'
    | '/_authenticated/client/payments/$id'
    | '/_authenticated/client/projects/$id'
    | '/_authenticated/client/projects/new'
    | '/_authenticated/client/services/$id'
    | '/_authenticated/client/support/$id'
    | '/_authenticated/admin/clients/'
    | '/_authenticated/admin/project-requests/'
    | '/_authenticated/client/projects/'
    | '/_authenticated/admin/clients/$id/edit'
    | '/_authenticated/client/projects/requests/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcceptableUseRoute: typeof AcceptableUseRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  LoginOtpRoute: typeof LoginOtpRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProcessRoute: typeof ProcessRoute
  SlaRoute: typeof SlaRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRouteWithChildren
  WhyRoute: typeof WhyRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sla': {
      id: '/sla'
      path: '/sla'
      fullPath: '/sla'
      preLoaderRoute: typeof SlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-otp': {
      id: '/login-otp'
      path: '/login-otp'
      fullPath: '/login-otp'
      preLoaderRoute: typeof LoginOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/_authenticated/client': {
      id: '/_authenticated/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof AuthenticatedClientRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/': {
      id: '/_authenticated/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof AuthenticatedClientIndexRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/verify/receipt/$code': {
      id: '/verify/receipt/$code'
      path: '/receipt/$code'
      fullPath: '/verify/receipt/$code'
      preLoaderRoute: typeof VerifyReceiptCodeRouteImport
      parentRoute: typeof VerifyRoute
    }
    '/_authenticated/client/wallet': {
      id: '/_authenticated/client/wallet'
      path: '/wallet'
      fullPath: '/client/wallet'
      preLoaderRoute: typeof AuthenticatedClientWalletRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/support': {
      id: '/_authenticated/client/support'
      path: '/support'
      fullPath: '/client/support'
      preLoaderRoute: typeof AuthenticatedClientSupportRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/services': {
      id: '/_authenticated/client/services'
      path: '/services'
      fullPath: '/client/services'
      preLoaderRoute: typeof AuthenticatedClientServicesRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/projects': {
      id: '/_authenticated/client/projects'
      path: '/projects'
      fullPath: '/client/projects'
      preLoaderRoute: typeof AuthenticatedClientProjectsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/profile': {
      id: '/_authenticated/client/profile'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof AuthenticatedClientProfileRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/payments': {
      id: '/_authenticated/client/payments'
      path: '/payments'
      fullPath: '/client/payments'
      preLoaderRoute: typeof AuthenticatedClientPaymentsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/notifications': {
      id: '/_authenticated/client/notifications'
      path: '/notifications'
      fullPath: '/client/notifications'
      preLoaderRoute: typeof AuthenticatedClientNotificationsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/invoices': {
      id: '/_authenticated/client/invoices'
      path: '/invoices'
      fullPath: '/client/invoices'
      preLoaderRoute: typeof AuthenticatedClientInvoicesRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/files': {
      id: '/_authenticated/client/files'
      path: '/files'
      fullPath: '/client/files'
      preLoaderRoute: typeof AuthenticatedClientFilesRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/contracts': {
      id: '/_authenticated/client/contracts'
      path: '/contracts'
      fullPath: '/client/contracts'
      preLoaderRoute: typeof AuthenticatedClientContractsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/admin/wallet': {
      id: '/_authenticated/admin/wallet'
      path: '/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AuthenticatedAdminWalletRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/project-requests': {
      id: '/_authenticated/admin/project-requests'
      path: '/project-requests'
      fullPath: '/admin/project-requests'
      preLoaderRoute: typeof AuthenticatedAdminProjectRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/files': {
      id: '/_authenticated/admin/files'
      path: '/files'
      fullPath: '/admin/files'
      preLoaderRoute: typeof AuthenticatedAdminFilesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contracts': {
      id: '/_authenticated/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AuthenticatedAdminContractsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit-log': {
      id: '/_authenticated/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/client/projects/': {
      id: '/_authenticated/client/projects/'
      path: '/'
      fullPath: '/client/projects/'
      preLoaderRoute: typeof AuthenticatedClientProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedClientProjectsRoute
    }
    '/_authenticated/admin/project-requests/': {
      id: '/_authenticated/admin/project-requests/'
      path: '/'
      fullPath: '/admin/project-requests/'
      preLoaderRoute: typeof AuthenticatedAdminProjectRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminProjectRequestsRoute
    }
    '/_authenticated/admin/clients/': {
      id: '/_authenticated/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AuthenticatedAdminClientsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/client/support/$id': {
      id: '/_authenticated/client/support/$id'
      path: '/$id'
      fullPath: '/client/support/$id'
      preLoaderRoute: typeof AuthenticatedClientSupportIdRouteImport
      parentRoute: typeof AuthenticatedClientSupportRoute
    }
    '/_authenticated/client/services/$id': {
      id: '/_authenticated/client/services/$id'
      path: '/$id'
      fullPath: '/client/services/$id'
      preLoaderRoute: typeof AuthenticatedClientServicesIdRouteImport
      parentRoute: typeof AuthenticatedClientServicesRoute
    }
    '/_authenticated/client/projects/new': {
      id: '/_authenticated/client/projects/new'
      path: '/new'
      fullPath: '/client/projects/new'
      preLoaderRoute: typeof AuthenticatedClientProjectsNewRouteImport
      parentRoute: typeof AuthenticatedClientProjectsRoute
    }
    '/_authenticated/client/projects/$id': {
      id: '/_authenticated/client/projects/$id'
      path: '/$id'
      fullPath: '/client/projects/$id'
      preLoaderRoute: typeof AuthenticatedClientProjectsIdRouteImport
      parentRoute: typeof AuthenticatedClientProjectsRoute
    }
    '/_authenticated/client/payments/$id': {
      id: '/_authenticated/client/payments/$id'
      path: '/$id'
      fullPath: '/client/payments/$id'
      preLoaderRoute: typeof AuthenticatedClientPaymentsIdRouteImport
      parentRoute: typeof AuthenticatedClientPaymentsRoute
    }
    '/_authenticated/client/invoices/$id': {
      id: '/_authenticated/client/invoices/$id'
      path: '/$id'
      fullPath: '/client/invoices/$id'
      preLoaderRoute: typeof AuthenticatedClientInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedClientInvoicesRoute
    }
    '/_authenticated/client/contracts/$id': {
      id: '/_authenticated/client/contracts/$id'
      path: '/$id'
      fullPath: '/client/contracts/$id'
      preLoaderRoute: typeof AuthenticatedClientContractsIdRouteImport
      parentRoute: typeof AuthenticatedClientContractsRoute
    }
    '/_authenticated/admin/support/$id': {
      id: '/_authenticated/admin/support/$id'
      path: '/$id'
      fullPath: '/admin/support/$id'
      preLoaderRoute: typeof AuthenticatedAdminSupportIdRouteImport
      parentRoute: typeof AuthenticatedAdminSupportRoute
    }
    '/_authenticated/admin/projects/$id': {
      id: '/_authenticated/admin/projects/$id'
      path: '/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIdRouteImport
      parentRoute: typeof AuthenticatedAdminProjectsRoute
    }
    '/_authenticated/admin/project-requests/$id': {
      id: '/_authenticated/admin/project-requests/$id'
      path: '/$id'
      fullPath: '/admin/project-requests/$id'
      preLoaderRoute: typeof AuthenticatedAdminProjectRequestsIdRouteImport
      parentRoute: typeof AuthenticatedAdminProjectRequestsRoute
    }
    '/_authenticated/admin/payments/$id': {
      id: '/_authenticated/admin/payments/$id'
      path: '/$id'
      fullPath: '/admin/payments/$id'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsIdRouteImport
      parentRoute: typeof AuthenticatedAdminPaymentsRoute
    }
    '/_authenticated/admin/invoices/$id': {
      id: '/_authenticated/admin/invoices/$id'
      path: '/$id'
      fullPath: '/admin/invoices/$id'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedAdminInvoicesRoute
    }
    '/_authenticated/admin/contracts/$id': {
      id: '/_authenticated/admin/contracts/$id'
      path: '/$id'
      fullPath: '/admin/contracts/$id'
      preLoaderRoute: typeof AuthenticatedAdminContractsIdRouteImport
      parentRoute: typeof AuthenticatedAdminContractsRoute
    }
    '/_authenticated/admin/clients/new': {
      id: '/_authenticated/admin/clients/new'
      path: '/clients/new'
      fullPath: '/admin/clients/new'
      preLoaderRoute: typeof AuthenticatedAdminClientsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients/$id': {
      id: '/_authenticated/admin/clients/$id'
      path: '/clients/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/client/projects/requests/$id': {
      id: '/_authenticated/client/projects/requests/$id'
      path: '/requests/$id'
      fullPath: '/client/projects/requests/$id'
      preLoaderRoute: typeof AuthenticatedClientProjectsRequestsIdRouteImport
      parentRoute: typeof AuthenticatedClientProjectsRoute
    }
    '/_authenticated/admin/clients/$id/edit': {
      id: '/_authenticated/admin/clients/$id/edit'
      path: '/edit'
      fullPath: '/admin/clients/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminClientsIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminClientsIdRoute
    }
  }
}

interface AuthenticatedAdminContractsRouteChildren {
  AuthenticatedAdminContractsIdRoute: typeof AuthenticatedAdminContractsIdRoute
}

const AuthenticatedAdminContractsRouteChildren: AuthenticatedAdminContractsRouteChildren =
  {
    AuthenticatedAdminContractsIdRoute: AuthenticatedAdminContractsIdRoute,
  }

const AuthenticatedAdminContractsRouteWithChildren =
  AuthenticatedAdminContractsRoute._addFileChildren(
    AuthenticatedAdminContractsRouteChildren,
  )

interface AuthenticatedAdminInvoicesRouteChildren {
  AuthenticatedAdminInvoicesIdRoute: typeof AuthenticatedAdminInvoicesIdRoute
}

const AuthenticatedAdminInvoicesRouteChildren: AuthenticatedAdminInvoicesRouteChildren =
  {
    AuthenticatedAdminInvoicesIdRoute: AuthenticatedAdminInvoicesIdRoute,
  }

const AuthenticatedAdminInvoicesRouteWithChildren =
  AuthenticatedAdminInvoicesRoute._addFileChildren(
    AuthenticatedAdminInvoicesRouteChildren,
  )

interface AuthenticatedAdminPaymentsRouteChildren {
  AuthenticatedAdminPaymentsIdRoute: typeof AuthenticatedAdminPaymentsIdRoute
}

const AuthenticatedAdminPaymentsRouteChildren: AuthenticatedAdminPaymentsRouteChildren =
  {
    AuthenticatedAdminPaymentsIdRoute: AuthenticatedAdminPaymentsIdRoute,
  }

const AuthenticatedAdminPaymentsRouteWithChildren =
  AuthenticatedAdminPaymentsRoute._addFileChildren(
    AuthenticatedAdminPaymentsRouteChildren,
  )

interface AuthenticatedAdminProjectRequestsRouteChildren {
  AuthenticatedAdminProjectRequestsIdRoute: typeof AuthenticatedAdminProjectRequestsIdRoute
  AuthenticatedAdminProjectRequestsIndexRoute: typeof AuthenticatedAdminProjectRequestsIndexRoute
}

const AuthenticatedAdminProjectRequestsRouteChildren: AuthenticatedAdminProjectRequestsRouteChildren =
  {
    AuthenticatedAdminProjectRequestsIdRoute:
      AuthenticatedAdminProjectRequestsIdRoute,
    AuthenticatedAdminProjectRequestsIndexRoute:
      AuthenticatedAdminProjectRequestsIndexRoute,
  }

const AuthenticatedAdminProjectRequestsRouteWithChildren =
  AuthenticatedAdminProjectRequestsRoute._addFileChildren(
    AuthenticatedAdminProjectRequestsRouteChildren,
  )

interface AuthenticatedAdminProjectsRouteChildren {
  AuthenticatedAdminProjectsIdRoute: typeof AuthenticatedAdminProjectsIdRoute
}

const AuthenticatedAdminProjectsRouteChildren: AuthenticatedAdminProjectsRouteChildren =
  {
    AuthenticatedAdminProjectsIdRoute: AuthenticatedAdminProjectsIdRoute,
  }

const AuthenticatedAdminProjectsRouteWithChildren =
  AuthenticatedAdminProjectsRoute._addFileChildren(
    AuthenticatedAdminProjectsRouteChildren,
  )

interface AuthenticatedAdminSupportRouteChildren {
  AuthenticatedAdminSupportIdRoute: typeof AuthenticatedAdminSupportIdRoute
}

const AuthenticatedAdminSupportRouteChildren: AuthenticatedAdminSupportRouteChildren =
  {
    AuthenticatedAdminSupportIdRoute: AuthenticatedAdminSupportIdRoute,
  }

const AuthenticatedAdminSupportRouteWithChildren =
  AuthenticatedAdminSupportRoute._addFileChildren(
    AuthenticatedAdminSupportRouteChildren,
  )

interface AuthenticatedAdminClientsIdRouteChildren {
  AuthenticatedAdminClientsIdEditRoute: typeof AuthenticatedAdminClientsIdEditRoute
}

const AuthenticatedAdminClientsIdRouteChildren: AuthenticatedAdminClientsIdRouteChildren =
  {
    AuthenticatedAdminClientsIdEditRoute: AuthenticatedAdminClientsIdEditRoute,
  }

const AuthenticatedAdminClientsIdRouteWithChildren =
  AuthenticatedAdminClientsIdRoute._addFileChildren(
    AuthenticatedAdminClientsIdRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditLogRoute: typeof AuthenticatedAdminAuditLogRoute
  AuthenticatedAdminContractsRoute: typeof AuthenticatedAdminContractsRouteWithChildren
  AuthenticatedAdminFilesRoute: typeof AuthenticatedAdminFilesRoute
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRouteWithChildren
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRouteWithChildren
  AuthenticatedAdminProjectRequestsRoute: typeof AuthenticatedAdminProjectRequestsRouteWithChildren
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRouteWithChildren
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWalletRoute: typeof AuthenticatedAdminWalletRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminClientsIdRoute: typeof AuthenticatedAdminClientsIdRouteWithChildren
  AuthenticatedAdminClientsNewRoute: typeof AuthenticatedAdminClientsNewRoute
  AuthenticatedAdminClientsIndexRoute: typeof AuthenticatedAdminClientsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditLogRoute: AuthenticatedAdminAuditLogRoute,
  AuthenticatedAdminContractsRoute:
    AuthenticatedAdminContractsRouteWithChildren,
  AuthenticatedAdminFilesRoute: AuthenticatedAdminFilesRoute,
  AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRouteWithChildren,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRouteWithChildren,
  AuthenticatedAdminProjectRequestsRoute:
    AuthenticatedAdminProjectRequestsRouteWithChildren,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRouteWithChildren,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWalletRoute: AuthenticatedAdminWalletRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminClientsIdRoute:
    AuthenticatedAdminClientsIdRouteWithChildren,
  AuthenticatedAdminClientsNewRoute: AuthenticatedAdminClientsNewRoute,
  AuthenticatedAdminClientsIndexRoute: AuthenticatedAdminClientsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedClientContractsRouteChildren {
  AuthenticatedClientContractsIdRoute: typeof AuthenticatedClientContractsIdRoute
}

const AuthenticatedClientContractsRouteChildren: AuthenticatedClientContractsRouteChildren =
  {
    AuthenticatedClientContractsIdRoute: AuthenticatedClientContractsIdRoute,
  }

const AuthenticatedClientContractsRouteWithChildren =
  AuthenticatedClientContractsRoute._addFileChildren(
    AuthenticatedClientContractsRouteChildren,
  )

interface AuthenticatedClientInvoicesRouteChildren {
  AuthenticatedClientInvoicesIdRoute: typeof AuthenticatedClientInvoicesIdRoute
}

const AuthenticatedClientInvoicesRouteChildren: AuthenticatedClientInvoicesRouteChildren =
  {
    AuthenticatedClientInvoicesIdRoute: AuthenticatedClientInvoicesIdRoute,
  }

const AuthenticatedClientInvoicesRouteWithChildren =
  AuthenticatedClientInvoicesRoute._addFileChildren(
    AuthenticatedClientInvoicesRouteChildren,
  )

interface AuthenticatedClientPaymentsRouteChildren {
  AuthenticatedClientPaymentsIdRoute: typeof AuthenticatedClientPaymentsIdRoute
}

const AuthenticatedClientPaymentsRouteChildren: AuthenticatedClientPaymentsRouteChildren =
  {
    AuthenticatedClientPaymentsIdRoute: AuthenticatedClientPaymentsIdRoute,
  }

const AuthenticatedClientPaymentsRouteWithChildren =
  AuthenticatedClientPaymentsRoute._addFileChildren(
    AuthenticatedClientPaymentsRouteChildren,
  )

interface AuthenticatedClientProjectsRouteChildren {
  AuthenticatedClientProjectsIdRoute: typeof AuthenticatedClientProjectsIdRoute
  AuthenticatedClientProjectsNewRoute: typeof AuthenticatedClientProjectsNewRoute
  AuthenticatedClientProjectsIndexRoute: typeof AuthenticatedClientProjectsIndexRoute
  AuthenticatedClientProjectsRequestsIdRoute: typeof AuthenticatedClientProjectsRequestsIdRoute
}

const AuthenticatedClientProjectsRouteChildren: AuthenticatedClientProjectsRouteChildren =
  {
    AuthenticatedClientProjectsIdRoute: AuthenticatedClientProjectsIdRoute,
    AuthenticatedClientProjectsNewRoute: AuthenticatedClientProjectsNewRoute,
    AuthenticatedClientProjectsIndexRoute:
      AuthenticatedClientProjectsIndexRoute,
    AuthenticatedClientProjectsRequestsIdRoute:
      AuthenticatedClientProjectsRequestsIdRoute,
  }

const AuthenticatedClientProjectsRouteWithChildren =
  AuthenticatedClientProjectsRoute._addFileChildren(
    AuthenticatedClientProjectsRouteChildren,
  )

interface AuthenticatedClientServicesRouteChildren {
  AuthenticatedClientServicesIdRoute: typeof AuthenticatedClientServicesIdRoute
}

const AuthenticatedClientServicesRouteChildren: AuthenticatedClientServicesRouteChildren =
  {
    AuthenticatedClientServicesIdRoute: AuthenticatedClientServicesIdRoute,
  }

const AuthenticatedClientServicesRouteWithChildren =
  AuthenticatedClientServicesRoute._addFileChildren(
    AuthenticatedClientServicesRouteChildren,
  )

interface AuthenticatedClientSupportRouteChildren {
  AuthenticatedClientSupportIdRoute: typeof AuthenticatedClientSupportIdRoute
}

const AuthenticatedClientSupportRouteChildren: AuthenticatedClientSupportRouteChildren =
  {
    AuthenticatedClientSupportIdRoute: AuthenticatedClientSupportIdRoute,
  }

const AuthenticatedClientSupportRouteWithChildren =
  AuthenticatedClientSupportRoute._addFileChildren(
    AuthenticatedClientSupportRouteChildren,
  )

interface AuthenticatedClientRouteChildren {
  AuthenticatedClientContractsRoute: typeof AuthenticatedClientContractsRouteWithChildren
  AuthenticatedClientFilesRoute: typeof AuthenticatedClientFilesRoute
  AuthenticatedClientInvoicesRoute: typeof AuthenticatedClientInvoicesRouteWithChildren
  AuthenticatedClientNotificationsRoute: typeof AuthenticatedClientNotificationsRoute
  AuthenticatedClientPaymentsRoute: typeof AuthenticatedClientPaymentsRouteWithChildren
  AuthenticatedClientProfileRoute: typeof AuthenticatedClientProfileRoute
  AuthenticatedClientProjectsRoute: typeof AuthenticatedClientProjectsRouteWithChildren
  AuthenticatedClientServicesRoute: typeof AuthenticatedClientServicesRouteWithChildren
  AuthenticatedClientSupportRoute: typeof AuthenticatedClientSupportRouteWithChildren
  AuthenticatedClientWalletRoute: typeof AuthenticatedClientWalletRoute
  AuthenticatedClientIndexRoute: typeof AuthenticatedClientIndexRoute
}

const AuthenticatedClientRouteChildren: AuthenticatedClientRouteChildren = {
  AuthenticatedClientContractsRoute:
    AuthenticatedClientContractsRouteWithChildren,
  AuthenticatedClientFilesRoute: AuthenticatedClientFilesRoute,
  AuthenticatedClientInvoicesRoute:
    AuthenticatedClientInvoicesRouteWithChildren,
  AuthenticatedClientNotificationsRoute: AuthenticatedClientNotificationsRoute,
  AuthenticatedClientPaymentsRoute:
    AuthenticatedClientPaymentsRouteWithChildren,
  AuthenticatedClientProfileRoute: AuthenticatedClientProfileRoute,
  AuthenticatedClientProjectsRoute:
    AuthenticatedClientProjectsRouteWithChildren,
  AuthenticatedClientServicesRoute:
    AuthenticatedClientServicesRouteWithChildren,
  AuthenticatedClientSupportRoute: AuthenticatedClientSupportRouteWithChildren,
  AuthenticatedClientWalletRoute: AuthenticatedClientWalletRoute,
  AuthenticatedClientIndexRoute: AuthenticatedClientIndexRoute,
}

const AuthenticatedClientRouteWithChildren =
  AuthenticatedClientRoute._addFileChildren(AuthenticatedClientRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedClientRoute: typeof AuthenticatedClientRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedClientRoute: AuthenticatedClientRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface VerifyRouteChildren {
  VerifyReceiptCodeRoute: typeof VerifyReceiptCodeRoute
}

const VerifyRouteChildren: VerifyRouteChildren = {
  VerifyReceiptCodeRoute: VerifyReceiptCodeRoute,
}

const VerifyRouteWithChildren =
  VerifyRoute._addFileChildren(VerifyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AcceptableUseRoute: AcceptableUseRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  LoginOtpRoute: LoginOtpRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProcessRoute: ProcessRoute,
  SlaRoute: SlaRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRouteWithChildren,
  WhyRoute: WhyRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
