/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyRouteImport } from './routes/why'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SlaRouteImport } from './routes/sla'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as AuthenticatedClientRouteImport } from './routes/_authenticated/client'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedClientIndexRouteImport } from './routes/_authenticated/client.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedClientSupportRouteImport } from './routes/_authenticated/client.support'
import { Route as AuthenticatedClientServicesRouteImport } from './routes/_authenticated/client.services'
import { Route as AuthenticatedClientProjectsRouteImport } from './routes/_authenticated/client.projects'
import { Route as AuthenticatedClientProfileRouteImport } from './routes/_authenticated/client.profile'
import { Route as AuthenticatedClientPaymentsRouteImport } from './routes/_authenticated/client.payments'
import { Route as AuthenticatedClientNotificationsRouteImport } from './routes/_authenticated/client.notifications'
import { Route as AuthenticatedClientInvoicesRouteImport } from './routes/_authenticated/client.invoices'
import { Route as AuthenticatedClientFilesRouteImport } from './routes/_authenticated/client.files'
import { Route as AuthenticatedClientContractsRouteImport } from './routes/_authenticated/client.contracts'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin.invoices'
import { Route as AuthenticatedAdminFilesRouteImport } from './routes/_authenticated/admin.files'
import { Route as AuthenticatedAdminContractsRouteImport } from './routes/_authenticated/admin.contracts'
import { Route as AuthenticatedAdminAuditLogRouteImport } from './routes/_authenticated/admin.audit-log'
import { Route as AuthenticatedAdminClientsIndexRouteImport } from './routes/_authenticated/admin.clients.index'
import { Route as AuthenticatedAdminClientsNewRouteImport } from './routes/_authenticated/admin.clients.new'
import { Route as AuthenticatedAdminClientsIdRouteImport } from './routes/_authenticated/admin.clients.$id'
import { Route as AuthenticatedAdminClientsIdEditRouteImport } from './routes/_authenticated/admin.clients.$id.edit'

const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SlaRoute = SlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const AuthenticatedClientRoute = AuthenticatedClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientIndexRoute =
  AuthenticatedClientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedClientSupportRoute =
  AuthenticatedClientSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientServicesRoute =
  AuthenticatedClientServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientProjectsRoute =
  AuthenticatedClientProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientProfileRoute =
  AuthenticatedClientProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientPaymentsRoute =
  AuthenticatedClientPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientNotificationsRoute =
  AuthenticatedClientNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientInvoicesRoute =
  AuthenticatedClientInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientFilesRoute =
  AuthenticatedClientFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientContractsRoute =
  AuthenticatedClientContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFilesRoute = AuthenticatedAdminFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminContractsRoute =
  AuthenticatedAdminContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditLogRoute =
  AuthenticatedAdminAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsIndexRoute =
  AuthenticatedAdminClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsNewRoute =
  AuthenticatedAdminClientsNewRouteImport.update({
    id: '/clients/new',
    path: '/clients/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsIdRoute =
  AuthenticatedAdminClientsIdRouteImport.update({
    id: '/clients/$id',
    path: '/clients/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsIdEditRoute =
  AuthenticatedAdminClientsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedAdminClientsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/sla': typeof SlaRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/why': typeof WhyRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/client': typeof AuthenticatedClientRouteWithChildren
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/admin/files': typeof AuthenticatedAdminFilesRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/client/contracts': typeof AuthenticatedClientContractsRoute
  '/client/files': typeof AuthenticatedClientFilesRoute
  '/client/invoices': typeof AuthenticatedClientInvoicesRoute
  '/client/notifications': typeof AuthenticatedClientNotificationsRoute
  '/client/payments': typeof AuthenticatedClientPaymentsRoute
  '/client/profile': typeof AuthenticatedClientProfileRoute
  '/client/projects': typeof AuthenticatedClientProjectsRoute
  '/client/services': typeof AuthenticatedClientServicesRoute
  '/client/support': typeof AuthenticatedClientSupportRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/client/': typeof AuthenticatedClientIndexRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRouteWithChildren
  '/admin/clients/new': typeof AuthenticatedAdminClientsNewRoute
  '/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/clients/$id/edit': typeof AuthenticatedAdminClientsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/sla': typeof SlaRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/why': typeof WhyRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services': typeof ServicesIndexRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/admin/files': typeof AuthenticatedAdminFilesRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/client/contracts': typeof AuthenticatedClientContractsRoute
  '/client/files': typeof AuthenticatedClientFilesRoute
  '/client/invoices': typeof AuthenticatedClientInvoicesRoute
  '/client/notifications': typeof AuthenticatedClientNotificationsRoute
  '/client/payments': typeof AuthenticatedClientPaymentsRoute
  '/client/profile': typeof AuthenticatedClientProfileRoute
  '/client/projects': typeof AuthenticatedClientProjectsRoute
  '/client/services': typeof AuthenticatedClientServicesRoute
  '/client/support': typeof AuthenticatedClientSupportRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/client': typeof AuthenticatedClientIndexRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRouteWithChildren
  '/admin/clients/new': typeof AuthenticatedAdminClientsNewRoute
  '/admin/clients': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/clients/$id/edit': typeof AuthenticatedAdminClientsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/sla': typeof SlaRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/why': typeof WhyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/client': typeof AuthenticatedClientRouteWithChildren
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/_authenticated/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/_authenticated/admin/files': typeof AuthenticatedAdminFilesRoute
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/client/contracts': typeof AuthenticatedClientContractsRoute
  '/_authenticated/client/files': typeof AuthenticatedClientFilesRoute
  '/_authenticated/client/invoices': typeof AuthenticatedClientInvoicesRoute
  '/_authenticated/client/notifications': typeof AuthenticatedClientNotificationsRoute
  '/_authenticated/client/payments': typeof AuthenticatedClientPaymentsRoute
  '/_authenticated/client/profile': typeof AuthenticatedClientProfileRoute
  '/_authenticated/client/projects': typeof AuthenticatedClientProjectsRoute
  '/_authenticated/client/services': typeof AuthenticatedClientServicesRoute
  '/_authenticated/client/support': typeof AuthenticatedClientSupportRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/client/': typeof AuthenticatedClientIndexRoute
  '/_authenticated/admin/clients/$id': typeof AuthenticatedAdminClientsIdRouteWithChildren
  '/_authenticated/admin/clients/new': typeof AuthenticatedAdminClientsNewRoute
  '/_authenticated/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/_authenticated/admin/clients/$id/edit': typeof AuthenticatedAdminClientsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/acceptable-use'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/portfolio'
    | '/privacy'
    | '/process'
    | '/sla'
    | '/support'
    | '/terms'
    | '/why'
    | '/admin'
    | '/client'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/services/'
    | '/admin/audit-log'
    | '/admin/contracts'
    | '/admin/files'
    | '/admin/invoices'
    | '/admin/payments'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/client/contracts'
    | '/client/files'
    | '/client/invoices'
    | '/client/notifications'
    | '/client/payments'
    | '/client/profile'
    | '/client/projects'
    | '/client/services'
    | '/client/support'
    | '/admin/'
    | '/client/'
    | '/admin/clients/$id'
    | '/admin/clients/new'
    | '/admin/clients/'
    | '/admin/clients/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/acceptable-use'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/portfolio'
    | '/privacy'
    | '/process'
    | '/sla'
    | '/support'
    | '/terms'
    | '/why'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/services'
    | '/admin/audit-log'
    | '/admin/contracts'
    | '/admin/files'
    | '/admin/invoices'
    | '/admin/payments'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/client/contracts'
    | '/client/files'
    | '/client/invoices'
    | '/client/notifications'
    | '/client/payments'
    | '/client/profile'
    | '/client/projects'
    | '/client/services'
    | '/client/support'
    | '/admin'
    | '/client'
    | '/admin/clients/$id'
    | '/admin/clients/new'
    | '/admin/clients'
    | '/admin/clients/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/acceptable-use'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/portfolio'
    | '/privacy'
    | '/process'
    | '/sla'
    | '/support'
    | '/terms'
    | '/why'
    | '/_authenticated/admin'
    | '/_authenticated/client'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/services/'
    | '/_authenticated/admin/audit-log'
    | '/_authenticated/admin/contracts'
    | '/_authenticated/admin/files'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/users'
    | '/_authenticated/client/contracts'
    | '/_authenticated/client/files'
    | '/_authenticated/client/invoices'
    | '/_authenticated/client/notifications'
    | '/_authenticated/client/payments'
    | '/_authenticated/client/profile'
    | '/_authenticated/client/projects'
    | '/_authenticated/client/services'
    | '/_authenticated/client/support'
    | '/_authenticated/admin/'
    | '/_authenticated/client/'
    | '/_authenticated/admin/clients/$id'
    | '/_authenticated/admin/clients/new'
    | '/_authenticated/admin/clients/'
    | '/_authenticated/admin/clients/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcceptableUseRoute: typeof AcceptableUseRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProcessRoute: typeof ProcessRoute
  SlaRoute: typeof SlaRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  WhyRoute: typeof WhyRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sla': {
      id: '/sla'
      path: '/sla'
      fullPath: '/sla'
      preLoaderRoute: typeof SlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/_authenticated/client': {
      id: '/_authenticated/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof AuthenticatedClientRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/': {
      id: '/_authenticated/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof AuthenticatedClientIndexRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/client/support': {
      id: '/_authenticated/client/support'
      path: '/support'
      fullPath: '/client/support'
      preLoaderRoute: typeof AuthenticatedClientSupportRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/services': {
      id: '/_authenticated/client/services'
      path: '/services'
      fullPath: '/client/services'
      preLoaderRoute: typeof AuthenticatedClientServicesRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/projects': {
      id: '/_authenticated/client/projects'
      path: '/projects'
      fullPath: '/client/projects'
      preLoaderRoute: typeof AuthenticatedClientProjectsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/profile': {
      id: '/_authenticated/client/profile'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof AuthenticatedClientProfileRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/payments': {
      id: '/_authenticated/client/payments'
      path: '/payments'
      fullPath: '/client/payments'
      preLoaderRoute: typeof AuthenticatedClientPaymentsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/notifications': {
      id: '/_authenticated/client/notifications'
      path: '/notifications'
      fullPath: '/client/notifications'
      preLoaderRoute: typeof AuthenticatedClientNotificationsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/invoices': {
      id: '/_authenticated/client/invoices'
      path: '/invoices'
      fullPath: '/client/invoices'
      preLoaderRoute: typeof AuthenticatedClientInvoicesRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/files': {
      id: '/_authenticated/client/files'
      path: '/files'
      fullPath: '/client/files'
      preLoaderRoute: typeof AuthenticatedClientFilesRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/contracts': {
      id: '/_authenticated/client/contracts'
      path: '/contracts'
      fullPath: '/client/contracts'
      preLoaderRoute: typeof AuthenticatedClientContractsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/files': {
      id: '/_authenticated/admin/files'
      path: '/files'
      fullPath: '/admin/files'
      preLoaderRoute: typeof AuthenticatedAdminFilesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contracts': {
      id: '/_authenticated/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AuthenticatedAdminContractsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit-log': {
      id: '/_authenticated/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients/': {
      id: '/_authenticated/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AuthenticatedAdminClientsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients/new': {
      id: '/_authenticated/admin/clients/new'
      path: '/clients/new'
      fullPath: '/admin/clients/new'
      preLoaderRoute: typeof AuthenticatedAdminClientsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients/$id': {
      id: '/_authenticated/admin/clients/$id'
      path: '/clients/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients/$id/edit': {
      id: '/_authenticated/admin/clients/$id/edit'
      path: '/edit'
      fullPath: '/admin/clients/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminClientsIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminClientsIdRoute
    }
  }
}

interface AuthenticatedAdminClientsIdRouteChildren {
  AuthenticatedAdminClientsIdEditRoute: typeof AuthenticatedAdminClientsIdEditRoute
}

const AuthenticatedAdminClientsIdRouteChildren: AuthenticatedAdminClientsIdRouteChildren =
  {
    AuthenticatedAdminClientsIdEditRoute: AuthenticatedAdminClientsIdEditRoute,
  }

const AuthenticatedAdminClientsIdRouteWithChildren =
  AuthenticatedAdminClientsIdRoute._addFileChildren(
    AuthenticatedAdminClientsIdRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditLogRoute: typeof AuthenticatedAdminAuditLogRoute
  AuthenticatedAdminContractsRoute: typeof AuthenticatedAdminContractsRoute
  AuthenticatedAdminFilesRoute: typeof AuthenticatedAdminFilesRoute
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminClientsIdRoute: typeof AuthenticatedAdminClientsIdRouteWithChildren
  AuthenticatedAdminClientsNewRoute: typeof AuthenticatedAdminClientsNewRoute
  AuthenticatedAdminClientsIndexRoute: typeof AuthenticatedAdminClientsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditLogRoute: AuthenticatedAdminAuditLogRoute,
  AuthenticatedAdminContractsRoute: AuthenticatedAdminContractsRoute,
  AuthenticatedAdminFilesRoute: AuthenticatedAdminFilesRoute,
  AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminClientsIdRoute:
    AuthenticatedAdminClientsIdRouteWithChildren,
  AuthenticatedAdminClientsNewRoute: AuthenticatedAdminClientsNewRoute,
  AuthenticatedAdminClientsIndexRoute: AuthenticatedAdminClientsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedClientRouteChildren {
  AuthenticatedClientContractsRoute: typeof AuthenticatedClientContractsRoute
  AuthenticatedClientFilesRoute: typeof AuthenticatedClientFilesRoute
  AuthenticatedClientInvoicesRoute: typeof AuthenticatedClientInvoicesRoute
  AuthenticatedClientNotificationsRoute: typeof AuthenticatedClientNotificationsRoute
  AuthenticatedClientPaymentsRoute: typeof AuthenticatedClientPaymentsRoute
  AuthenticatedClientProfileRoute: typeof AuthenticatedClientProfileRoute
  AuthenticatedClientProjectsRoute: typeof AuthenticatedClientProjectsRoute
  AuthenticatedClientServicesRoute: typeof AuthenticatedClientServicesRoute
  AuthenticatedClientSupportRoute: typeof AuthenticatedClientSupportRoute
  AuthenticatedClientIndexRoute: typeof AuthenticatedClientIndexRoute
}

const AuthenticatedClientRouteChildren: AuthenticatedClientRouteChildren = {
  AuthenticatedClientContractsRoute: AuthenticatedClientContractsRoute,
  AuthenticatedClientFilesRoute: AuthenticatedClientFilesRoute,
  AuthenticatedClientInvoicesRoute: AuthenticatedClientInvoicesRoute,
  AuthenticatedClientNotificationsRoute: AuthenticatedClientNotificationsRoute,
  AuthenticatedClientPaymentsRoute: AuthenticatedClientPaymentsRoute,
  AuthenticatedClientProfileRoute: AuthenticatedClientProfileRoute,
  AuthenticatedClientProjectsRoute: AuthenticatedClientProjectsRoute,
  AuthenticatedClientServicesRoute: AuthenticatedClientServicesRoute,
  AuthenticatedClientSupportRoute: AuthenticatedClientSupportRoute,
  AuthenticatedClientIndexRoute: AuthenticatedClientIndexRoute,
}

const AuthenticatedClientRouteWithChildren =
  AuthenticatedClientRoute._addFileChildren(AuthenticatedClientRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedClientRoute: typeof AuthenticatedClientRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedClientRoute: AuthenticatedClientRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AcceptableUseRoute: AcceptableUseRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProcessRoute: ProcessRoute,
  SlaRoute: SlaRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  WhyRoute: WhyRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
